defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

development:
  <<: *defaults
  database: grad_gift_development

test:
  <<: *defaults
  database: grad_gift_test
  w: 0

production:
  <<: *defaults
  host: ds027489.mongolab.com
  port: 27489
  database: heroku_app21445121
  username: emk411
  password: 2404john